### ISSUE TITLE
bootique-jersey-jackson: Support java.time serialization

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jersey#53]
Proper (de)serialization of `java.time` objects requires installing Jackson extensions. Doing it in the context of `bootique-jersey-jackson` is a real pain. So let's enable this feature by default, but also do some refactoring to make ObjectMapper creation factory-driven, so that a single mapper can be configured for the entire app with some common policies:

```yaml
jerseyjackson:
   // same as "JerseyJacksonModule.extend(b).skipNullProperties()"
   skipNullProperties: true
```
