### ISSUE TITLE
JerseyClientInstrumentedModule - better names for healthchecks, consistent config

### ISSUE THREAD

**Issue by andrus** [bootique/bootique-jersey#80]
Jersey Client metrics thresholds are configured like this:
```yaml
jerseyclientinstrumented:
  timeRequestsThresholds:
    warning: 1
    critical: 5
```
There are two issues with this:

1. The thresholds are actually for "the number of requests per minute" (with exponential decay). This is not clear from the threshold name
2. Configuration structure is different from Jetty and Hikari (e.g. on Jetty it would be `jetty.health.xyzThresholds`)

## Upgrade Notes

To upgrade to the new version, you must check for explicit threshold configurations with name "timeRequestsThresholds" and replace them with a new structure as follows:
```yaml
# The old structure looked like this:
#jerseyclientinstrumented:
#  timeRequestsThresholds:
#    warning: 1
#    critical: 5

# The new should look like this:
jerseyclient:
  health:
    requestsPerMin:
      warning: 1
      critical: 5
```
Also the reported metric got renamed from `bq.JerseyClient.Threshold.Requests` to `bq.JerseyClient.Requests.PerMin`.
